apiVersion: v2
name: xray-proxy
description: Xray-core SOCKS5-прокси с исходящим VLESS+Reality
type: application
version: 1.0.3
appVersion: "v1.0.0"
maintainers:
  - name: gvpaleev
    url: https://github.com/gvpaleev
sources:
  - https://github.com/gvpaleev/xray-proxy-chart
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - kind: fixed
      description: Fix image tag reference in annotations (26.3.27 → v1.0.0)
  artifacthub.io/images: |
    - name: xray-proxy
      image: docker.io/gvpaleevkz/xray-proxy:v1.0.0
  artifacthub.io/links: |
    - name: Docker Hub
      url: https://hub.docker.com/repository/docker/gvpaleevkz/xray-proxy/general
    - name: Xray-core
      url: https://github.com/XTLS/Xray-core
