apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xray-proxy.fullname" . }}-config
  labels:
    {{- include "xray-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {
      "log": {
        "loglevel": "{{ .Values.xray.logLevel }}"
      },
      "dns": {
        "servers": {{ .Values.xray.dns.servers | toJson }}
      },
      "inbounds": [
        {
          "tag": "{{ .Values.xray.routing.sourceTag }}",
          "port": {{ .Values.xray.socksPort }},
          "listen": "0.0.0.0",
          "protocol": "socks",
          "settings": {
            "udp": true
          }
        }
      ],
      "outbounds": [
        {
          "tag": "{{ .Values.xray.routing.outboundTag }}",
          "protocol": "vless",
          "settings": {
            "vnext": [
              {
                "address": "{{ .Values.xray.vless.address }}",
                "port": {{ .Values.xray.vless.port }},
                "users": [
                  {
                    "id": "{{ .Values.xray.vless.userId }}",
                    "encryption": "{{ .Values.xray.vless.encryption }}",
                    "flow": "{{ .Values.xray.vless.flow }}"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "serverName": "{{ .Values.xray.reality.serverName }}",
              "fingerprint": "{{ .Values.xray.reality.fingerprint }}",
              "publicKey": "{{ .Values.xray.reality.publicKey }}",
              "shortId": "{{ .Values.xray.reality.shortId }}",
              "spiderX": "{{ .Values.xray.reality.spiderX }}"
            }
          }
        }
      ],
      "routing": {
        "rules": [
          {
            "type": "field",
            "inboundTag": ["{{ .Values.xray.routing.sourceTag }}"],
            "outboundTag": "{{ .Values.xray.routing.outboundTag }}"
          }
        ]
      }
    }
