name: Release Chart

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and push
        run: |
          helm package ./chart
          helm push xray-proxy-*.tgz oci://ghcr.io/${{ github.repository_owner }}
